name: u_tweet

description: "A new Flutter project."
publish_to: 'none' # Remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  appwrite: ^15.0.0
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.4.9 
  fpdart: ^0.5.0
  image_picker: ^1.1.2
  timeago: ^3.3.0
  http: ^1.3.0
  
   

  any_link_preview: ^3.0.3
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
